### ISSUE TITLE
I get an error when I use 'xb build' and 'xb devenv'; how do I run this?

### ISSUE THREAD

**Issue by xmicro** [benvanik/xenia#381]
Traceback (most recent call last):
  File "xenia-build", line 1009, in <module>
    main()
  File "xenia-build", line 86, in main
    return_code = command.execute(args, pass_args, os.getcwd())
  File "xenia-build", line 530, in execute
    result = super(BuildCommand, self).execute(args, pass_args, cwd)
  File "xenia-build", line 496, in execute
    pass_args, throw_on_error=False)
  File "xenia-build", line 174, in shell_call
    result = subprocess.call(command, shell=False, stdout=stdout_file)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by benvanik** [comment]
You either don't have Visual Studio 2015 installed or are not running the build script from the Visual Studio Developer Command Prompt. Ensure you can run 'devenv' on its own from the command prompt - if you can't, fix that.
