### ISSUE TITLE
Error in xb build

### ISSUE THREAD

**Issue by BrouliKing** [benvanik/xenia#571]
When I run xb build i have some error with missing file...

```
f:\git\xenia>xb build
Building debug...

- running premake...
Building configurations...
Running action 'vs2015'...
Done (733ms).

- building (all):debug...
Traceback (most recent call last):
  File "xenia-build", line 1233, in <module>
    main()
  File "xenia-build", line 86, in main
    return_code = command.execute(args, pass_args, os.getcwd())
  File "xenia-build", line 620, in execute
    result = super(BuildCommand, self).execute(args, pass_args, cwd)
  File "xenia-build", line 586, in execute
    pass_args, throw_on_error=False)
  File "xenia-build", line 194, in shell_call
    result = subprocess.call(command, shell=False, stdout=stdout_file)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Nie mo┐na odnalečŠ okreťlonego pliku - that mean can't find a file/some file is missing
```

**Comment by BrouliKing** [comment]
of, i find the solution, i used wrong command line.
